name: Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:


  semgrep-static-code-analysis:
    name: "semgrep checks"
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Scanning code on ${{ matrix.os }}
        continue-on-error: false
        run: |
          # Install semgrep rather than using a container due to:
          # https://github.com/actions/checkout/issues/334
          sudo apt install python3-pip || apt install python3-pip
          pip3 install semgrep
          semgrep --config semgrep.yaml $(pwd)/portal-ui --error
