name: Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  no-warnings-and-make-assets:
    name: "React Code Has No Warnings & is Prettified, then Make Assets"
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x ]
        os: [ ubuntu-latest ]
    steps:
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        name: Yarn Cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./portal-ui/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./portal-ui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        id: assets-cache
        name: Assets Cache
        with:
          path: |
            ./portal-ui/build/
          key: ${{ runner.os }}-assets-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-assets-
      - name: Install Dependencies
        working-directory: ./portal-ui
        continue-on-error: false
        run: |
          yarn install
      - name: Check for Warnings in build output
        working-directory: ./portal-ui
        continue-on-error: false
        run: |
          ./check-warnings.sh
      - name: Check if Files are Prettified
        working-directory: ./portal-ui
        continue-on-error: false
        run: |
          ./check-prettier.sh
