name: Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  lint-job-for-containers:
    name: Checking Lint
    runs-on: self-hosted
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Lint Job Test
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make lint-for-containers
